### ISSUE TITLE
sheriffderek link leads to 404 error

### ISSUE THREAD

**Issue by TareUhhhhhh** [perpetual-education/alpha-three-homepage#1]
https://github.com/perpetual-education/alpha-three-homepage/blob/f4c448d210fbeb45e27a604a0590dbfec18c19dc/index.html#L28

**Comment by perpetual-education** [comment]
His folder name was 'sheriff' ! not sheriffderek, silly guy. Fixed in #34fb1369c6420eeea407232ec80169030190bcc2
